a,b,c = map(int, input().split())
setnum = min(a,b,c)
bugers = sorted(list(map(int, input().split())), reverse=True)
side = sorted(list(map(int, input().split())), reverse=True)
beverage = sorted(list(map(int, input().split())), reverse=True)
sale = int((sum(bugers[:setnum]) + sum(side[:setnum]) + sum(beverage[:setnum]))* 0.9) +sum(bugers[setnum:]) +sum(side[setnum:]) +sum(beverage[setnum:])
price = sum(bugers)+sum(side)+sum(beverage)
print(price)
print(sale)
